pharma/urls.py
from django.contrib import admin
from django.urls import path
from pharma.views.landing_page import LandingPageView
from .views.index import Index , store
from .views.cart import Cart
from .views.checkout import CheckOut
from .views.orders import OrderView
from .views.signup import Signup
from .views.login import Login , logout
from pharma.views.contact import contact, success

app_name = 'pharma'
urlpatterns = [
    path('', LandingPageView.as_view(), name='landing_page'),
    path('index/', Index.as_view(), name='index'),
    path('store/', store, name='store'),
    path('cart/', Cart.as_view(), name='cart'),
    path('check-out/', CheckOut.as_view(), name='checkout'),
    path('orders/all/', OrderView.as_view(), name='all_orders'),
    path('orders/', OrderView.as_view()),
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout , name='logout'),
    path('contact.html/', contact, name='contact'),
    path('success/', success, name='success'),
]

pshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pharma.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pharma/models/category.py
from django.db import models


class Category(models.Model):
    # Fields
    name = models.CharField(max_length=200)

    # Methods
    def __str__(self):
        """
        String representation of the Catagory object.
        This is used for display in the admin & other contexts.
        """
        return self.name

    @staticmethod
    def get_categories():
        """
        Returns all categories.
        A static method is used for simplicity,
        """
        return Category.objects.all()

pharma/models/contact.py
from django.db import models


class Contact(models.Model):
    # Faields
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.CharField(max_length=500)

    # Methods
    def __str__(self):
        """
        String representation of the Contact object.
        This is used for display purposes in the admin & other contexts.
        """
        return self.name

pharma/models/customer.py
from django.db import models


class Customer(models.Model):
    # Fields
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=10)
    address = models.CharField(max_length=500)
    email = models.EmailField()
    password = models.CharField(max_length=200)

    def register(self):
        """
        Register a customer by saving thier object to the database
        """
        self.save()

    def __str__(self):
        """
        String representation of the Customer object.
        This is used for display in the admin & other contexts.
        """
        return f'{self.first_name} {self.last_name}'

    def isExists(self):
        """
        Check if a customer with given email already exists.
        Returns True if exists, else False.
        """
        return Customer.objects.filter(email=self.email).exists()

    @staticmethod
    def get_customer_by_email(email):
        """
        Retrive a customer by thier email address.
        Returns the customer oject if found, else None.
        """
        try:
            return Customer.objects.get(email=email)
        except Customer.DoesNotExist:
            return None

pharma/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

pharma/views/cart.py
from django.shortcuts import render, redirect
from pharma.models.customer import Customer
from django.views import View
from pharma.models.product import Product
from pharma.models.order import Order


class Cart(View):
    """
    Handles the display of the shopping cart.

    GET:
    - Retrieves product IDs from the session.
    - Retrieves corresponding products.
    - Renders the cart page with the list of products.
    """
    def get(self, request):
        # Retrieve product IDs from the session cart
        ids = list(request.session.get('cart').keys())
        # Retrieve products based on the IDs
        products = Product.get_products_by_id(ids)
        # Debug: print the retrived products
        print(products)
        # Render the cart pagewith the list of products
        return render(request, 'pharma/cart.html', {'products': products})

pharma/views/checkout.py
from django.shortcuts import render, redirect
from pharma.models.customer import Customer
from django.views import View
from pharma.models.product import Product
from pharma.models.order import Order


class CheckOut(View):
    """
    Handles the checkout process.

    POST:
    - Retrieves address, phone, customer ID, and cart data from the request.
    - Retrieves products based on the IDs in the cart.
    - Creates an anonymous customer if no logged-in customer.
    - Creates orders for each product in the cart.
    - Clears the cart in the session.
    - Redirects to the cart page.
    """

    def post(self, request):
        # Retrieve address, phone, customer ID, and cart data from the request
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        customer_id = request.session.get('customer')
        cart = request.session.get('cart')

        # Retrieve products based on the IDs in the cart
        products = Product.get_products_by_id(list(cart.keys()))

        # Debug: print the retrieved data
        print(address, phone, customer_id, cart, products)

        # If there's no logged-in customer, create an anonymous customer
        if customer_id is None or not Customer.objects.filter(id=customer_id).exists():
            customer = Customer.objects.create(first_name='Anonymous', email='anonymous@example.com')
        else:
            customer = Customer.objects.get(id=customer_id)

        # Create orders for each product in the cart
        for product in products:
            print(cart.get(str(product.id)))
            order = Order.objects.create(customer=customer,
                          product=product,
                          price=product.price,
                          address=address,
                          phone=phone,
                          quantity=cart.get(str(product.id)))
            order.save()
        
        # Clear the cart in the session
        request.session['cart'] = {}

        # Redirect to the cart page
        return redirect('pharma:cart')

pharma/views/contact.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from django.core.mail import send_mail
from pharma.contact.forms import ContactForm
from pharma.models.contact import Contact

def contact(request):
    """
    Handles the contact form submission.
    On POST, validates the form, saves the data to the database,
    and redirects to the success page.
    On GET, renders the contact form.
    """
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # save the form data to the database
            contact = Contact.objects.create(
                name=form.cleaned_data['name'],
                email=form.cleaned_data['email'],
                message=form.cleaned_data['message']
            )
            # send an email to the contact
            """send_mail(
                'Thank you for contacting us',
                'We have received your message and will get back to you soon.',
                'pharma@example.com',
                [email],
                fail_silently=False,) """
            # Redirect to the success page
            return redirect('pharma:success')
    else:
        form = ContactForm()
    return render(request, 'pharma/contact.html', {'form': form})

def success(request):
    """
    Renders the success page after a successful contact form submission.
    """
    message = 'Thank you for contacting us!'
    return render(request, 'pharma/success.html', {'message': message})

pharma/views/index.py
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect
from django.views import View
from pharma.models.product import Product
from pharma.models.category import Category


# Index class inherits from Django's View class
class Index(View):
    # Handles POST requests
    def post(self, request):
        # Get product and remove flag from the POST data
        product = request.POST.get('product')
        remove = request.POST.get('remove')

        # Get the cart from the session, defaulting to an empty dictionary
        # if it doesn't exist
        cart = request.session.get('cart', {})

        # Update the quantity of the product in the cart
        cart[product] = self.update_cart_quantity(cart, product, remove)

        # Update the session cart
        request.session['cart'] = cart

        print('cart', request.session['cart'])
        return HttpResponseRedirect(reverse('pharma:store'))

    # Handles GET requests
    def get(self, request):
        return HttpResponseRedirect(f'/store{request.get_full_path()[1:]}')

    # Static method to update the quantity of a product in the cart
    def post(self, request):
        product = request.POST.get('product')
        remove = request.POST.get('remove')
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(product)
            if quantity:
                if remove:
                    if quantity <= 1:
                        cart.pop(product)
                    else:
                        cart[product] = quantity-1
                else:
                    cart[product] = quantity+1

            else:
                cart[product] = 1
        else:
            cart = {}
            cart[product] = 1

        request.session['cart'] = cart
        print('cart', request.session['cart'])
        return redirect('pharma:store')


# Function to handle the store view

def store(request):
    # Ensure the session has a cart, even if it's empty
    request.session.setdefault('cart', {})

    # Get the category ID from the GET parameters
    categoryID = request.GET.get('category')

    # Get the products for the given category,
    # or all products if no category is specified
    products = Product.get_products_by_category(categoryID) if categoryID else Product.objects.all()

    # Get all categories
    categories = Category.objects.all()

    # Prepare the data for the template
    data = {
        'products': products,
        'categories': categories,
    }
    return render(request, 'pharma/index.html', data)

pharma/views/landing_page.py
from django.views.generic import TemplateView

class LandingPageView(TemplateView):
    """
    Renders the landing page.

    Uses a template to display the landing page content.
    """
    template_name = 'pharma/landing_page.html'

pharma/views/login.py
from django.shortcuts import render , redirect , HttpResponseRedirect
from django.contrib.auth.hashers import  check_password
from pharma.models.customer import Customer
from django.views import View


class Login(View):
    """
    Handles user login.

    GET:
    - Renders the login page.

    POST:
    - Validates user credentials.
    - Logs in the user if valid.
    - Redirects to the specified return URL or the store page.
    """
    return_url = None

    def get(self, request):
        # Store the return URL from the query parameters
        Login.return_url = request.GET.get ('return_url')
        return render (request, 'pharma/login.html')

    def post(self, request):
        # Get user credentials from the form
        email = request.POST.get ('email')
        password = request.POST.get ('password')
        # Retrieve the customer based on the provided email
        customer = Customer.get_customer_by_email (email)
        error_message = None
        if customer:
            # Check if the password is valid
            flag = check_password (password, customer.password)
            if flag:
                # Log in the user and set the customer ID in the session
                request.session['customer'] = customer.id

                # Redirect to the return URL or the store page
                if Login.return_url:
                    return HttpResponseRedirect (Login.return_url)
                else:
                    Login.return_url = None
                    return redirect ('pharma:store')
            else:
                error_message = 'Invalid !!'
        else:
            error_message = 'Invalid !!'

        print (email, password)
        return render (request, 'pharma/login.html', {'error': error_message})

def logout(request):
    """
    Logs out the user by clearing the session.
    Redirects to the login page after logout.
    """
    request.session.clear()
    return redirect('pharma:login')

pharma/views/orders.py
from django.shortcuts import render, redirect
from pharma.models.customer import Customer
from django.views import View
from pharma.models.product import Product
from pharma.models.order import Order

class OrderView(View):
    """
    Handles the display of orders.

    GET:
    - Retrieves the customer ID from the session.
    - Fetches orders based on the customer ID for logged-in users.
    - Fetches all orders for anonymous users.
    - Renders the orders page with the list of orders.
    """
    
    
    def get(self, request):
        # Retrieve the customer ID from the session
        customer = request.session.get('customer')
        
        if customer:
            # Fetch orders for logged-in users
            orders = Order.get_orders_by_customer(customer)
        else:
            # Fetch orders for anonymous users (you may customize this logic)
            orders = Order.get_all_orders()

        # Debug: print the retrieved orders
        print("Orders:", orders)

        # Render the orders page with the list of orders
        return render(request, 'pharma/orders.html', {'orders': orders})

pharma/views/signup.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.hashers import make_password
from pharma.models.customer import Customer
from django.views import View


class Signup (View):
    """
    Handles user signup.

    GET:
    - Renders the signup page.

    POST:
    - Processes user signup form data.
    - Validates form data.
    - Creates a new customer if the data is valid.
    - Redirects to the store page on successful signup.
    """
    
    def get(self, request):
        # Render the signup page
        return render (request, 'pharma/signup.html')

    def post(self, request):
        # Get form data from the request 
        postData = request.POST
        first_name = postData.get ('firstname')
        last_name = postData.get ('lastname')
        phone = postData.get ('phone')
        email = postData.get ('email')
        password = postData.get ('password')
        
        # validation
        value = {
            'first_name': first_name,
            'last_name': last_name,
            'phone': phone,
            'email': email
        }
        error_message = None

        # Create a new customer instance
        customer = Customer (first_name=first_name,
                             last_name=last_name,
                             phone=phone,
                             email=email,
                             password=password)
        # Validate the customer data
        error_message = self.validateCustomer (customer)

        if not error_message:
            # Hash the password and register the customer
            print (first_name, last_name, phone, email, password)
            customer.password = make_password (customer.password)
            customer.register ()
            return redirect('pharma:store')
        else:
            # Render the signup page with an error message and the entered values
            data = {
                'error': error_message,
                'values': value
            }
            return render (request, 'pharma/signup.html', data)

    def validateCustomer(self, customer):
        """
        Validates customer data.

        Returns an error message if validation fails.
        """
        error_message = None
        if (not customer.first_name):
            error_message = "Please Enter your First Name !!"
        elif len (customer.first_name) < 3:
            error_message = 'First Name must be 3 char long or more'
        elif not customer.last_name:
            error_message = 'Please Enter your Last Name'
        elif len (customer.last_name) < 3:
            error_message = 'Last Name must be 3 char long or more'
        elif not customer.phone:
            error_message = 'Enter your Phone Number'
        elif len (customer.phone) < 10:
            error_message = 'Phone Number must be 10 char Long'
        elif len (customer.password) < 5:
            error_message = 'Password must be 5 char long'
        elif len (customer.email) < 5:
            error_message = 'Email must be 5 char long'
        elif customer.isExists ():
            error_message = 'Email Address Already Registered..'
        # saving

        return error_message
    
    

pharma/templates/pharma/cart.html
{% extends 'base.html' %}


{% block content %}
{% load cart %}
{% load custom_filter %}

<style>
    body {
        background-color: #00000048; /* Set your desired grey color */
    }
</style>
<div class="container">
   <div class="border rounded p-4 m-4">
        <p class="display-4 pl-4 ml-4 btn btn-success rounded-pill">Your Cart</p>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th>Sno.</th>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                
                {% for product in products %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><img style="height: 80px;" class="rounded-circle" src="{{product.image.url}}" alt=""></td>
                    <td>{{product.name}}</td>
                    <td>{{product.price|currency}}</td>
                    <td>{{product|cart_quantity:request.session.cart}}</td>
                    <td>{{product|price_total:request.session.cart|currency}}</td>
                </tr>

                {% endfor %}
               
            </tbody>

            <tfoot>
                <tr>
                    <th colspan="4"></th>
                    <th class="" colspan="">Total</th>
                    <th>{{products|total_cart_price:request.session.cart|currency}}</th>
                </tr>
            </tfoot>
        </table>
        <hr>
        <div class="m-3 p-3">
            <a href="#" data-toggle="modal" data-target="#exampleModal" class="btn btn-outline-success border rounded  col-lg-3 float-right">Check out</a>
        </div>
   </div>
</div>


<!-- modal -->

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
              Check Out Form
          </h5>
          <hr>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="m-2 p-3">
            <form action="/check-out/" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="">Address</label>
                  <input type="text" name="address" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  
                </div>
                <div class="form-group">
                    <label for="">Phone</label>
                    <input type="text" name="phone" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  </div>

                  <input type="submit" class="btn float-right btn-outline-success col-lg-6" value="Check out">
            </form>
          </div>
        </div>
        
      </div>
    </div>
  </div>



{% endblock %}

pharma/templates/pharma/index.html
{% extends 'base.html' %}

{% block content %}
{% load cart %}
{% load custom_filter %}

<style>
    body {
        background-color: #00000048; /* Set your desired grey color */
    }

    /* Update button colors */
    .btn-success {
        background-color: #ff7f50; /* Set your desired orange color */
        border-color: #ff7f50;
    }

    /* Update the "+" and "-" buttons inside the card footer */
    .card-footer .btn-success {
        background-color: #ff7f50; /* Set your desired orange color */
        border-color: #ff7f50;
    }
</style>

<!-- body -->
<div class="container-fluid mt-3">
    <div class="row">
        <!-- filter -->
        <div class="col-lg-3 mx-auto">
            <div class="list-group">
                <a href="{% url 'pharma:store' %}" class="list-group-item list-group-item-action btn btn-outline-success">All Products</a>
                {% for category in categories %}
                    <a href="{% url 'pharma:store' %}?category={{category.id}}" class="list-group-item list-group-item-action btn btn-outline-success ">{{category.name}}</a>
                {% endfor %}
            </div>
        </div>

        <!-- all products -->
        <div id='products' class="col-lg-9 mx-auto">
            <div class="row mx-auto">
                {% for product in products %}
                    <div class="card mx-auto mb-3" id={{product.id}} style="width: 18rem;">
                        <img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}">
                        <div class="card-body">
                            <h5 class="card-title">{{product.name}}</h5>
                            <p class="card-text">{{product.description}}</p>
                            <p class="card-text"><b>{{product.price|currency}}</b></p>
                        </div>

                        <div class="card-footer p-0 no-gutters">
                            {% if product|is_in_cart:request.session.cart %}
                                <div class="row no-gutters">
                                    <form action="{% url 'pharma:index' %}" class="col-2 " method="post">
                                        {% csrf_token %}
                                        <input hidden type="text" name='product' value='{{product.id}}'>
                                        <input hidden type="text" name='remove' value='True'>
                                        <input type="submit" value=" - " class="btn btn-block btn-success border-right">
                                    </form>
                                    <div class="text-center col btn btn-success">{{product|cart_quantity:request.session.cart}} in Cart</div>
                                    <form action="{% url 'pharma:index' %}" class="col-2 " method="post">
                                        {% csrf_token %}
                                        <input hidden type="text" name='product' value='{{product.id}}'>
                                        <input type="submit" value=" + " class="btn btn-block btn-success border-left">
                                    </form>
                                </div>
                            {% else %}
                                <form action="{% url 'pharma:index' %}" method="POST" class="btn-block">
                                    {% csrf_token %}
                                    <input hidden type="text" name='product' value='{{product.id}}'>
                                    <input type="submit" class="float-right btn btn-success form-control" value="Add To Cart">
                                </form>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

pharma/templates/pharma/landing_page.html
<!-- landing_page.html -->
{% extends 'base.html' %}

{% block content %}
    <iframe src="https://ismaelabdulahi1.wixsite.com/p-shop" width="100%" height="800px"></iframe>
    <a href="http://127.0.0.1:8000/store">Visit Store</a>
{% endblock %}

pharma/templates/pharma/login.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>

    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
            font-family: 'Roboto', sans-serif;
            background: gray;
        }

        .box {
            width: 350px;
            height: 400px;
            padding: 45px;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-align: center;
            box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);
        }

        .box h1 {
            text-transform: uppercase;
            color: #0074E4;
        }

        .box input[type="text"],
        .box input[type="password"] {
            border: 0;
            background: none;
            display: block;
            margin: 25px auto;
            text-align: center;
            outline: none;
            padding: 12px 12px;
            width: 245px;
            color: #fff;
            border-bottom: 1px solid #264E86;  /* Add this line to mimic the focus effect */
        }

        .box input[type="submit"] {
            outline: none;
            background: #90B77D;
            border: none;
            padding: 8px 16px;
            color: #fff;
            font-weight: 800;
            cursor: pointer;  /* Add this line to indicate the submit button is clickable */
        }

        .box input[type="submit"]:hover {
            background: #43A047;
            -webkit-transition: background 0.3s ease-in-out;
            -moz-transition: background 0.3s ease-in-out;
            transition: background-color 0.3s ease-in-out;
        }
    </style>
</head>

<body>
    <div class="box">
        <form action="{% url 'pharma:login' %}" method="post">
            {% csrf_token %}
            <h1>Login</h1>
            <input type="text" name="email" placeholder="Email" required>
            <input type="password" name="password" placeholder="Password" required>
            <input type="submit" value="Login">
        </form>

        <footer class="ftr">
            <p>&copy; <span>Iso</span></p>
        </footer>
    </div>
</body>

</html>
{% endblock %}

pharma/templates/pharma/signup.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>

    <!-- Add your custom styles here -->
    <style>
        .container {
            height: 100vh;
            width: 100%;
            align-items: center;
            display: flex;
            justify-content: center;
            background-image: radial-gradient(
                circle farthest-corner at 10% 20%,
                rgba(0, 0, 0, 0) 0%,
                rgba(0, 0, 0, 0.008) 90%
            );
        }

        .card {
            border-radius: 10px;
            box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.3);
            width: 400px;
            height: 440px;
            background-color: #ffffff;
            padding: 10px 30px;
        }

        .card_title {
            text-align: center;
            padding: 10px;
        }

        .card_title h1 {
            font-size: 26px;
            font-weight: bold;
        }

        .form input {
            margin: 10px 0;
            width: 100%;
            background-color: #e2e2e2;
            border: none;
            outline: none;
            padding: 12px 20px;
            border-radius: 4px;
        }

        .form button {
            background-color: #4796ff;
            color: #ffffff;
            font-size: 16px;
            outline: none;
            border-radius: 5px;
            border: none;
            padding: 8px 15px;
            width: 100%;
        }

        .card_terms {
            display: flex;
            align-items: center;
            padding: 10px;
        }

        .card_terms input[type="checkbox"] {
            background-color: #e2e2e2;
            padding-top: 5px;
        }

        .card_terms span {
            margin: 5px;
            font-size: 13px;
        }

        .card a {
            color: #4796ff;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card_title">
                <h1>Create Account</h1>
                <span>Already have an account? <a href="{% url 'pharma:login' %}">Sign In</a></span>
            </div>
            <div class="form">
                <form action="{% url 'pharma:signup' %}" method="POST">
                    {% csrf_token %}

                    {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{error}}
                    </div>
                    {% endif %}

                    <!-- First Name -->
                    <input type="text" name="firstname" value="{{values.first_name}}" placeholder="First Name" />

                    <!-- Last Name -->
                    <input type="text" name="lastname" value="{{values.last_name}}" placeholder="Last Name" />

                    <!-- Phone -->
                    <input type="text" name="phone" value="{{values.phone}}" placeholder="9876543210" />

                    <!-- Email -->
                    <input type="email" name="email" value="{{values.email}}" placeholder="abc@gmail.com" />

                    <!-- Password -->
                    <input type="password" name="password" placeholder="Password" />

                    <!-- Checkme button -->
                    <div class="mb-3 form-check">
                        <label class="form-check-label d-grid gap-2" for="exampleCheck1">I have read and agree to the <a href="#">Terms of Service</a></label>
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    </div>

                    <button type="submit" class="btn btn-sm btn-success col-lg-12">Create an account</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}